
language: node_js
node_js: stable
# S: Build Lifecycle
install:
- npm install
#before_script:
# - npm install -g gulp
script:
- npm run build
after_script:
- cd dist
- ls
- git init
- git config user.name "jinxin0112"
- git config user.email "m18508218948@163.com"
- git add .
- git commit -m 'deploy'
- git push --force --quiet "https://2d70e5cea6a439d8d38c1a8199af0793454ece67@${GH_REF}" master:master
# E: Build LifeCycle
branches:
only:
- dev
env:
global:
- GH_REF: github.com/Alkaids/Alkaids.github.io.git